### ISSUE TITLE
Strict mode + TypeError

### ISSUE THREAD

**Issue by mokorana** [shaack/cookie-consent-js#1]
`Uncaught TypeError: Cannot set property 'modal' of undefined
    at scripts.js:123`

**Comment by shaack** [comment]
Hi, `cookie-consent-js` has no file `scripts.js`.

**Comment by mokorana** [comment]
Yes, you are right. I just loaded your script as a module in my own scripts.js. Because I use strict mode, the error was displayed. I can deal with this by myself. I just wanted to let you know.

**Comment by shaack** [comment]
Okay, nice, but what exactly is the error? :)

**Comment by mokorana** [comment]
Problem is that `this` is undefined in `hideDialog()` and `showDialog()`. As a simple fix you could use `window.modal` instead.

**Comment by shaack** [comment]
Fixed. Thanks for reporting!
