### ISSUE TITLE
scss color variables should be set only if not already present

### ISSUE THREAD

**Issue by IvanRotrekl** [shaack/cookie-consent-js#4]
It would be useful,  if  sccs variables  $primary and  $secondary  were set with the !default directive:
```
$primary: #3579F6 !default; // "accept all" button and privacy policy link color
$secondary: #89a !default; // "accept necessary" button color
```
This way they would not  overwrite variables with the same names, which might already exist in a project...

https://github.com/shaack/cookie-consent-js/blob/e35c30980d361935533b128d0618ea1fdca3f23c/src/cookie-consent.scss#L1

**Comment by shaack** [comment]
Color variables are now more detailed and all !default
https://github.com/shaack/cookie-consent-js/blob/master/src/cookie-consent.scss
Thanks for reporting.
