### ISSUE TITLE
Czech language file

### ISSUE THREAD

**Issue by IvanRotrekl** [shaack/cookie-consent-js#6]
Hi, thank you for a  very useful script.  Could you please add this language file for the Czech language ? Regards Ivan
[cs.txt](https://github.com/shaack/cookie-consent-js/files/8763534/cs.txt)

**Comment by shaack** [comment]
Thanks for your contribution. I added the Language file with version 2.1.0.
https://github.com/shaack/cookie-consent-js/tree/master/cookie-consent-content
